### ISSUE TITLE
Populate Database

### ISSUE THREAD

**Issue by youngchan1694** [youngchan1694/find-dawgs#3]
## Description
Since, we are not hitting a public API with a full database, we need to generate our own data for this. Using the example in `index.ts` inside of the server folder, we can set up a new model instance. Might need to create script to generate data in the future. Please look at additional context for more details

## Requirements
- [x] Create more Dog object instances to populate the database
- [x] Add images of the dogs to the proper folder and add it to the object instances

## Additional Context
Check the `index.ts` file inside the 'server` folder and there should be an array of `Dog` objects in an array.

Example
```
new DogClasses.Dog(
    "Roger",
    "golden retriever.jpg",
    new DogClasses.Area("Atlanta", "Georgia", 30303),
    "Male",
    "Golden Retriever",
    2,
    true,
    76.5,
    [
      new DogClasses.Shot("distemper", new Date(2020, 11, 15)),
      new DogClasses.Shot("parvovirus", new Date(2020, 11, 15)),
      new DogClasses.Shot("hepatitis", new Date(2020, 11, 15)),
      new DogClasses.Shot("rabies", new Date(2020, 11, 15))
    ]
  )
```

Just remember, this is made with typescript so type checking is strict

**Comment by jsong941** [comment]
Completed. Added maltese.jpg in local folder. don't know how to publish this yet
